robot_base_frame: $(arg frame)base_footprint

footprint:
  [[-0.105, -0.105], [-0.105, 0.105], [0.105, 0.105], [0.105, -0.105]]
robot_radius: 0.113

inflation_radius: 1.0
cost_scaling_factor: 5.0

inscribed_radius: 0.113
circumscribed_radius: 0.113

obstacle_range: 3.0
raytrace_range: 3.5

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)base_scan,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }

