update_frequency: 5.0
publish_frequency: 5.0
transform_tolerance: 0.2

static_map: false
rolling_window: true
width: 10.0
height: 10.0
resolution: 0.05

obstacle_range: 10.0
raytrace_range: 15.0

observation_sources: scan
