robot_base_frame: $(arg frame)base_link

footprint: [[-0.285, 0.285], [-0.285, -0.285], [0.285, -0.285], [0.285, 0.285]]
robot_radius: 0.267

inscribed_radius: 0.267
circumscribed_radius: 0.267

obstacle_range: 2.5
raytrace_range: 3.0

inflation_radius: 2.
cost_scaling_factor: 5.0

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)base_laser_front_link,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }