robot_base_frame: $(arg frame)base

footprint: [[-0.29, -0.19], [-0.29, 0.19], [0.29, 0.19], [0.29, -0.19]]
robot_radius: 0.267

inscribed_radius: 0.267
circumscribed_radius: 0.267

obstacle_range: 2.5
raytrace_range: 3.0

inflation_radius: 2.
cost_scaling_factor: 5.0

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: $(arg frame)laser_link,
    data_type: LaserScan,
    topic: $(arg namespace)/scan,
    marking: true,
    clearing: true,
  }